apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  labels:
    app: deployment-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-frontend
  template:
    metadata:
      labels: 
        app: deployment-frontend
    spec:
      containers:
      - name: frontend
        image: svvib19/sfc-frontend
