apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database
  labels:
    name: pvc-database
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi