apiVersion: v1
kind: Service
metadata:
  name: service-database
  labels:
    app: deployment-database
spec:
  type: ClusterIP
  selector:
    app: deployment-database
  ports:
    - protocol: TCP
      port: 6379
