name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  docker_username: ${{secrets.DOCKER_USERNAME}}
  docker_password: ${{secrets.DOCKER_PASSWORD}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...
  
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build backend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-build-backend.sh
      
    - name: Build frontend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-build-frontend.sh
      
    - name: Upload backend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-push-backend.sh
      
    - name: Upload frontend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-push-frontend.sh
