name: Workflow-Pull_request-main

on:
  pull_request:
    branches: [ main ]
    
env:
  docker_username: ${{secrets.DOCKER_USERNAME}}
  docker_password: ${{secrets.DOCKER_PASSWORD}}

jobs:
  pull_request-build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .


  pull_request-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  dockerhub-backend:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - uses: actions/checkout@v2
    
    - name: Build backend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-build-backend.sh
      
    - name: Upload backend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-push-backend.sh


  dockerhub-frontend:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - uses: actions/checkout@v2
      
    - name: Build frontend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-build-frontend.sh
      
    - name: Upload frontend image
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/sfc-docker-push-frontend.sh

  testing:
    runs-on: ubuntu-latest
    needs: [pull_request-build-frontend, pull_request-build-backend]
    steps:
    - uses: actions/checkout@v2

    - name: Bash test script
      run: bash ci/docker-compose-curl-test.sh
  

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: [dockerhub-frontend, dockerhub-backend]
    steps:
    - uses: actions/checkout@v2
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy pvc
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f kubernetes-pvc/
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy deployments and services
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: apply -f kubernetes/